WebApplication1/Controllers/AllComplaintsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AllComplaintsController : Controller
    {
        // GET: AllComplaints
        public ActionResult Index()
        {
            using (DbModel1 db1 = new DbModel1())
            {
                return View(db1.Customers.ToList());

            }
        }

        // GET: AllComplaints/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AllComplaints/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AllComplaints/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AllComplaints/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AllComplaints/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AllComplaints/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AllComplaints/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System;
using System.Web.Helpers;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class CustomerController : Controller
    {

        // GET: Customer
        public ActionResult Customers()
        {
            using (DbModel1 db1 = new DbModel1())
            {
            return View(db1.Customers.ToList());

            }
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            try
            {
                // TODO: Add insert logic here
                using (DbModel1 db1 = new DbModel1())
                {
                    db1.Customers.Add(customer);
                    db1.SaveChanges();
                }

                return RedirectToAction("Customers");
            }
            catch
            {
                return View();
            }



        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            using (DbModel1 db1 = new DbModel1())
            {
                return View(db1.Customers.Where(x => x.ID == id).FirstOrDefault());

            }
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Customer customer)
        {

            try
            {
                // TODO: Add delete logic here
                using (DbModel1 db1 = new DbModel1())
                {
                    customer = db1.Customers.Where(x => x.ID == id).FirstOrDefault();
                    db1.Customers.Remove(customer);
                    db1.SaveChanges();

                }

                return RedirectToAction("Customers");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/SCController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Web.UI.WebControls;
using System.Net.Mail;
using System.Net;
using System.Web;

namespace WebApplication1.Controllers
{
    public class SCController : Controller
    {
        // GET: SC
       
        

        
        public ActionResult Index()
        {
            using (DbModel1 db1 = new DbModel1())
            {
                return View(db1.Customers.ToList());

            }
        }

        // GET: SC/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SC/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SC/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SC/Edit/5
        public ActionResult Edit(int id)
        {
            using (DbModel1 db1 = new DbModel1())
            {
                return View(db1.Customers.Where(x => x.ID == id).FirstOrDefault());

            }
        }

        // POST: SC/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Customer customer)
        {
            try
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(customer.Customer_Email);
                // mail.To.Add("osamakiani32@gmail.com");
                mail.From = new MailAddress("artisticmania8@gmail.com", "KN Solutions");
                mail.Subject = "Confirmation Message ";
                string output = " Dear "+ customer.Customer_Name+" , \n We Resolve Your Complaint, \n Enjoy Yor Time With KN Solutions !! \n Thank You. ";
                mail.Body = output;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Credentials = new NetworkCredential("artisticmania8@gmail.com", "42Art91429142Art914291");
                smtp.EnableSsl = true;
                smtp.Send(mail);
                ViewBag.ErrorMessage = "Email send";


            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = "Email not found or matched";

            }
            try
            {
                // TODO: Add update logic here
                using (DbModel1 db1 = new DbModel1())
                {
                    db1.Entry(customer).State = EntityState.Modified;
                    db1.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SC/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SC/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/WhereController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class WhereController : Controller
    {
        // GET: Where
        public ActionResult Emp()
        {
            return View();
        }
        public ActionResult Index()
        {
            using (DbModel1 db1 = new DbModel1())
            {
                var drafts = db1.Customers.Where(d => d.Status == "Solved").ToList();
                return View(drafts);

            }
        }

        // GET: Where/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Where/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Where/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Where/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Where/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Where/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Where/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/styles/font-awesome.css" rel="stylesheet" />
    <link href="~/styles/style.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

WebApplication1/Views/_LayoutPage2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/styles/admin.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-sidebar collapsed">
                    MENU
                </button>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="GET" role="search">
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </form>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>  	<div class="container-fluid main-container">
        <div class="col-md-2 sidebar">
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <div class="absolute-wrapper"> </div>
                <!-- Menu -->
                <div class="side-menu" >
                    <nav class="navbar navbar-default" role="navigation">
                        <!-- Main Menu -->
                        <div class="side-menu-container">
                            <ul class="nav navbar-nav">
                                <li><a href='@Url.Action("Admin","Account")'><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
                                <li><a href='@Url.Action("Employee","Employee")'><span class="glyphicon glyphicon-plane"></span> Employees</a></li>
                                <li><a href='@Url.Action("Index","CustmerDetails")'><span class="glyphicon glyphicon-cloud"></span> Customers</a></li>
                                <li><a href='@Url.Action("Index","AllComplaints")'><span class="glyphicon glyphicon-plane"></span>All Complaints </a></li>
                                <li><a href='@Url.Action("Index","Where")'><span class="glyphicon glyphicon-cloud"></span>Solved Complaints </a></li>
                                <li><a href='@Url.Action("Login","Account")'><span class="glyphicon glyphicon-dashboard"></span> LogOut</a></li>

                                <!-- Dropdown-->
                                <li class="panel panel-default" id="dropdown">
                                    <a data-toggle="collapse" href="#dropdown-lvl1">
                                        <span ></span>  <span class="caret"></span>
                                    </a>

                                    <!-- Dropdown level 1 -->
                                    <div id="dropdown-lvl1" >
                                        <div class="panel-body">
                                            <ul class="nav navbar-nav">
                                                <li><a href="#"></a></li>
                                                <li><a href="#"></a></li>
                                                <li><a href="#"></a></li>

                                                <!-- Dropdown level 2 -->
                                                <li class="panel panel-default" id="dropdown">
                                                    <a data-toggle="collapse" href="#dropdown-lvl2">
                                                        <span ></span>  <span class="caret"></span>
                                                    </a>
                                                    <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                        <div class="panel-body">
                                                            <ul class="nav navbar-nav">
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>

                                <li><a href="#"><span ></span> </a></li>

                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>

                </div>
            </div>
        </div>
        <div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                  <b>  Admin Panell </b>
                </div>
                <div>
                    @RenderBody()
                </div>
                <footer class="pull-left footer">
                    <p class="col-md-12">
                        <hr class="divider">
                    <p>
                        <b>
                            © 2020 KN Solutions. All rights reserved | Design by
                            <a href="https://web.facebook.com/usama.haider.3194/" target="_blank">Osama HaiDer</a>
                        </b>
                    </p>
                    </p>
                </footer>            </div>
        </div>
        
    </div>
</body>
</html>

WebApplication1/Views/_LayoutPage3.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/styles/admin.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-sidebar collapsed">
                    MENU
                </button>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="GET" role="search">
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </form>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>  	<div class="container-fluid main-container">
        <div class="col-md-2 sidebar">
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <div class="absolute-wrapper"> </div>
                <!-- Menu -->
                <div class="side-menu">
                    <nav class="navbar navbar-default" role="navigation">
                        <!-- Main Menu -->
                        <div class="side-menu-container">
                            <ul class="nav navbar-nav">
                                <li><a href='@Url.Action("Emp","Where")'><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
                                <li><a href='@Url.Action("Customers","Customer")'><span class="glyphicon glyphicon-plane"></span> Add Complaints</a></li>
                                <li><a href='@Url.Action("Index","SC")'><span class="glyphicon glyphicon-cloud"></span> Solved Complaints</a></li>
                                <li><a href='@Url.Action("Login","Account")'><span class="glyphicon glyphicon-dashboard"></span> LogOut</a></li>
                                <li><a href="#"><span></span></a></li>
                                <li><a href="#"><span></span></a></li>

                                <!-- Dropdown-->
                                <li class="panel panel-default" id="dropdown">
                                    <a data-toggle="collapse" href="#dropdown-lvl1">
                                    </a>

                                    <!-- Dropdown level 1 -->
                                    <div id="dropdown-lvl1">
                                        <div class="panel-body">
                                            <ul class="nav navbar-nav">
                                                <li><a href="#"></a></li>
                                                <li><a href="#"></a></li>
                                                <li><a href="#"></a></li>

                                                <!-- Dropdown level 2 -->
                                                <li class="panel panel-default" id="dropdown">
                                                    <a data-toggle="collapse" href="#dropdown-lvl2">
                                                        <span></span> <span class="caret"></span>
                                                    </a>
                                                    <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                        <div class="panel-body">
                                                            <ul class="nav navbar-nav">
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>

                                <li><a href="#"><span></span> </a></li>

                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>

                </div>
            </div>
        </div>
        <div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                <b> Employee Panell </b>
                </div>
                <div>
                    @RenderBody()
                </div>
                <footer class="pull-left footer">
                    <p class="col-md-12">
                        <hr class="divider">
                    <p>
                        <b>
                            © 2020 KN Solutions. All rights reserved | Design by
                            <a href="https://web.facebook.com/usama.haider.3194/" target="_blank">Osama HaiDer</a>
                        </b>
                    </p>
                    </p>
                </footer>
            </div>
        </div>

    </div>
</body>
</html>